### ISSUE TITLE
Plugin override setting in config file dont_override

### ISSUE THREAD

**Issue by andypl78** [pimlie/authres_status#14]
Roundcube latest 1.2 and set in config file $config['dont_override'] = array('skin');
Plugin override this setting and show in configuration all available skins

![b16c5e3c-3fe3-11e6-8640-94793d4ea322](https://cloud.githubusercontent.com/assets/7813646/16581009/8d84e3a6-42a7-11e6-835b-9319646ff19a.jpg)

**Comment by Takika** [comment]
The sample config.inc.php.dist isn't too good. If you want to disable some authres_status config option, you have to add them to the dont_override array in the main config.inc.php file, not the plugins' config.

**Comment by andypl78** [comment]
Ok, 
File config.inc.php roundcube
`$config['dont_override'] = array('skin');`

File config.inc.php plugin authress
```
$config['enable_authres_status_column'] = true;
$config['use_fallback_verifier'] = false;
$config['show_statuses'] = authres_status::STATUS_ALL;
$config['dont_override'] = array('use_fallback_verifier');
```
This not working but I add to config.inc.php in plugin and now working
`$config['dont_override'] = array('use_fallback_verifier', 'skin');`

**Comment by johnwayne4d** [comment]
use the $config['don't_override'] in the main rc config, comment out the setting in the plugin's config.

**Comment by pimlie** [comment]
dont_override should always be set in the main config, also see this pull request: https://github.com/roundcube/roundcubemail/pull/5303
