### ISSUE TITLE
Status timeout

### ISSUE THREAD

**Issue by PeteLawler** [pimlie/authres_status#18]
Sometimes, the text in the mouse over box is very long and it doesn't display for enough time to be able to read it. It'd be useful to be able to either set a timeout on the box, or have it display for longer depending on the length of text being displayed.

**Comment by pimlie** [comment]
Unfortunately it's not possible to change that behaviour with the current implementation. That information is displayed using the [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) attribute, therefore your browser controls how long it is displayed etc.
