### ISSUE TITLE
Trusted MTAs

### ISSUE THREAD

**Issue by robin-thoni** [pimlie/authres_status#20]
The default configuration file does not include an example for the trusted MTAs:
```
//$config['trusted_mtas'] = array('mail.example.com');
$config['dont_override'][] = 'trusted_mtas'; //trusted_mtas should be blocked by default, that's an administrative security setting
```

**Comment by pimlie** [comment]
Thanks, added a default config.

Please see issue #14 about dont_override settings. They need to be set in the main config and cannot be set from a plugin config.

**Comment by robin-thoni** [comment]
Hmm, I put it in the authres_status config, and... It worked. Probably lucky, I'll change that.
Anyway, the example was the main issue.
