### ISSUE TITLE
angrychimp/php-dkim: @dev is not available anymore in Roundcube plugins repository

### ISSUE THREAD

**Issue by kalon33** [pimlie/authres_status#24]
It is not possible anymore to install authres_status using Composer as angrychimp/php-dkim: @dev dependency is not available anymore in the repository.

Could you please provide a fix?

**Comment by pimlie** [comment]
It seems still to be available [here](https://packagist.org/packages/angrychimp/php-dkim) 

Also if I remove the package and try to re-install it seems to work for me:
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing angrychimp/php-dkim (dev-master ac2adf8)
    Cloning ac2adf8bcd1bfe76b9c86208f12bf52e5ba88fe3

Generating autoload files
```

What error message do you get exactly?

**Comment by kalon33** [comment]
I get that error message when using composer from my roundcube install:
```
nicolas@caius-bonux:/var/www/datas/betamail# php composer.phar require roundcube/authres_status
Using version ^0.3.2 for roundcube/authres_status                                   
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for roundcube/authres_status ^0.3.2 -> satisfiable by roundcube/authres_status[0.3.2].
    - roundcube/authres_status 0.3.2 requires angrychimp/php-dkim @dev -> satisfiable by angrychimp/php-dkim[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by pimlie** [comment]
You probably need to add `"minimum-stability": "dev"` to your main `composer.json`? See [here](https://getcomposer.org/doc/04-schema.md#minimum-stability) for more info

**Comment by kalon33** [comment]
That was the problem. Thanks a lot, that fixed my bug. 

----- Mail original -----

De: "Pim" <notifications@github.com> 
À: "pimlie/authres_status" <authres_status@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 14 Juillet 2017 19:00:43 
Objet: Re: [pimlie/authres_status] angrychimp/php-dkim: @dev is not available anymore in Roundcube plugins repository (#24) 



You probably need to add "minimum-stability": "dev" to your main composer.json ? See here for more info
