### ISSUE TITLE
Show if a mail was transmitted and received with TLS

### ISSUE THREAD

**Issue by tomsommer** [pimlie/authres_status#30]
Like so: https://support.google.com/mail/answer/6330403?hl=en

By checking `Received:` headers

**Comment by pimlie** [comment]
Thanks for the suggestion. Allthough I like the idea, the main issue I have with this isssue is that its actually a bit out of the scope for this plugin. This plugin is currently only about the Authentication Status, hence its name. 
Adding support for other/more validation techniques are maybe better suited in a different plugin, what do you think?
